#!/usr/bin/env php
<?php
/*
 * This file is part of the PrestoPHP framework.
 *
 * (c) Gunnar Beushausen <gunnar@prestophp.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use PrestoPHP\Framework\CLI\Application;
use PrestoPHP\Framework\CLI\Command\AboutCommand;
use PrestoPHP\Framework\CLI\Command\GenerateCommand;
use PrestoPHP\Framework\CLI\Command\NewCommand;

require file_exists(__DIR__.'/vendor/autoload.php')
	? __DIR__.'/vendor/autoload.php'
	: __DIR__.'/../../autoload.php';

// Fix for Windows (Windows uses 'Path' instead of 'PATH'
if (!isset($_SERVER['PATH']) && isset($_SERVER['Path'])) {
	$_SERVER['PATH'] = $_SERVER['Path'];
}
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
$app = new Application('PrestoPHP');
$app->add(new AboutCommand());
$app->add(new GenerateCommand());
$app->add(new NewCommand());

$app->setDefaultCommand('about');

$app->run();